### ISSUE TITLE
Capture email addresses from Roles section

### ISSUE THREAD

**Issue by bwhm** [JoyStream/joystream-website#23]
Ref #20:
We need a GDPR complaint yet smooth way of having people sign up for mailchimp lists targeting each role.
For the inactive roles, the current design looks like this:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/35237943/54679358-600f9900-4b07-11e9-8d22-268eaea53672.png">
For the active roles, it looks like this:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/35237943/54679406-79184a00-4b07-11e9-888c-d66545906453.png">

---

#### Inactive roles  
1. As is the case for `Active roles` today, there should be a link to Rocket.Chat/Telegram (ask a question)
2. Remove the button saying “Send me a notification” (or at least make it non-clickable)
3. Either when someone clicks the `email` input field, or when someone starts typing, the field below should expand and show some extra information.
a. A button to check, accompanied by
b. A text field saying “Yes, I want to receive emails with updates on the status regarding the <role> role.”
c. Below this:
We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. [Learn more about Mailchimp's privacy practices here.](https://mailchimp.com/legal/)
d. Finally, a button saying “Sign me up”. (Or make it clickable _if_ the checkbox has been checked)
![image](https://user-images.githubusercontent.com/35237943/54679604-0196ea80-4b08-11e9-8124-1f9f4cf7691d.png)
4. When the information is submitted, The whole field should be replaced by a text field (and maybe an illustration?) saying:
---
### Subscription Confirmed  
Your subscription to our mailing list of people interested in receiving information and updates about the <role> role has been confirmed. Thank your for subscribing!  
If you want to interact with us, or other people interested in this role, go to Telegram/RocketChat.  
For questions about this list, contact hello@jsgenesis.com  
Jsgenesis AS  
C/O UMA Workspace  
Stenersgata 8  
0184 Oslo  
Norway  

---
#### Active roles  
In addition to the current buttons, we would also like for users to be able to sign up for lists with news/updates. It should be the same process as for `Inactive roles`, but still clear that they can indeed take this role on testnet today.  

---

#### Summary  
Feel free to play around how to exactly arrange this, but the final site must have the features described here. As we are using mailchimp, we may need someone to do some work in there as well.

**Comment by bwhm** [comment]
@TomiNadratowski @bedeho

**Comment by bedeho** [comment]
Done.
